name: Build and Release

on:
  push:
    branches:
      - main
      - 'feature/*'
    tags:
      - 'v*'

jobs:
  build:
    if: github.event_name == 'push' && (github.ref_type != 'tag')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure gradle.properties with secrets
        run: |
          cat > gradle.properties <<EOF
          signing.keyId=${{ secrets.SIGNING_KEY_ID }}
          signing.password=${{ secrets.SIGNING_PASSWORD }}
          signing.secretKeyRingFile=../secring.gpg
          mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}
          mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          EOF

      - name: Publish and Release to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache